# FastAgent配置文件

# 默认模型
default_model: deepseek-chat

# DeepSeek API配置
deepseek:
  base_url: "https://api.deepseek.com/v1"

# 日志配置
logger:
  type: "console"
  level: "info"
  progress_display: false
  show_chat: true
  show_tools: true
  truncate_tools: true

# MCP服务器配置
mcp:
  servers:
    context7-mcp:
      transport: "sse"
    fetch:
      transport: "sse"
